### ISSUE TITLE
issue with the animation:

### ISSUE THREAD

**Issue by Zahma** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#10]
I'm developing a Power BI Visual with this library.

The problem i'm facing, is that after applying a filter on some kind of data, the TWEEN animation for flows slows down, until it stops at the end.

is there any way to understand where the problem comes from. I think its related to moveTo() method from _animateCanvasLineSymbol . But I'm not sure.

**Comment by Zahma** [comment]
I'm developing a Power BI Visual with this library.

The problem i'm facing, is that after applying a filter on some kind of data, the TWEEN animation for flows slows down, until it stops at the end.

is there any way to understand where the problem comes from. I think its related to moveTo() method from _animateCanvasLineSymbol . But I'm not sure.

**Comment by jwasilgeo** [comment]
Is it possible to provide a standalone example illustrating this?  Are you saying you want the animation to repeat infinitely?  Is it running once and then never repeating again?  I want to first understand this better and rule out that this isn't something that can be set in the constructor options.

**Comment by Zahma** [comment]
would you please provide me with an email ? I'll send you a power BI link to see the example.

**Comment by jwasilgeo** [comment]
Can you copy/paste here just the lines of code for the layer constructor options when you are creating the layer?  I'm curious what that looks like.

**Comment by Zahma** [comment]
```
  var oneToManyFlowmapLayer = new CanvasFlowmap(geoJsonFeatureCollection, {
        originAndDestinationFieldIds: {
            originUniqueIdField: 'origin_city',
            originGeometry: {
                x: 'origin_lon',
                y: 'origin_lat',
                volume : 'volume'
            },
            destinationUniqueIdField: 'destination_city',
            destinationGeometry: {
                x: 'destination_lon',
                y: 'destination_lat'
            }
        },
        canvasBezierStyle: {
            type: 'simple',
            symbol: {
                // use canvas styling options (compare to CircleMarker styling below)
                strokeStyle: 'rgba(255, 0, 51, 0.8)',
                lineWidth: 1,
                lineCap: 'round',
                shadowColor: 'rgb(255, 0, 51)',
                shadowBlur: 1.5
            }
        },
        volumeMax: max,
        pathDisplayMode: 'all',
        animationStarted: true,
        animationEasingFamily: 'Linear',
        animationEasingType: 'None',
        animationDuration: 2000
    }).addTo(this.map);
```

**Comment by Zahma** [comment]
In fact the problem is with the Offset in:

 _valuesStart:
{offset: 189.26872136753735}
_valuesStartRepeat:
{offset: 189.26872136753735}

it supposed to be 0

**Comment by jwasilgeo** [comment]
Hey @Zahma I can see what you mean now in your live sample, especially after toggling to one of the other options.

Your layer constructor options look fine to me.

Where are these properties that you are referring to?

**Comment by Zahma** [comment]
I found after several research, Tween needs to set 				
`this._valuesStart[property] *= 1.0; // Ensures we're using numbers, not strings
`
to 0 line 215 of Tween library.

**Comment by jwasilgeo** [comment]
@Zahma please see this comment: https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/issues/5#issuecomment-331879108

**Comment by jwasilgeo** [comment]
Ok, closing for now.
