### ISSUE TITLE
Have the line not fully drawn to the end?

### ISSUE THREAD

**Issue by notflip** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#11]
Is it possible to have the line halfway? Or maybe at 75% of the path it has to follow? Great plugin thanks!

**Comment by jwasilgeo** [comment]
Glad you like the plugin!

We don't really have a way to do that now.  We rely on the native Canvas API to draw bezier curves and then stroke/draw the full lines from start to end.  This is an interesting resource, btw: https://pomax.github.io/bezierjs/.

You could for now, however, possibly create the _effect_ of only having the line partially drawn by overriding the dashed line and offset properties.  That's actually how the animated canvas effects are implemented.

**Comment by notflip** [comment]
That's a great idea! I'll see if I can find some information on dashed lines and the plugin.
Thank you!

**Comment by jwasilgeo** [comment]
It is doable, but unfortunately the place where we do that for the animated parts is pretty deep down in these 2 methods [on lines 632-652](https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/blob/master/src/CanvasFlowmapLayer.js#L632-L652).  You could add a few more canvas commands to the 1st method highlighted here to allow for line dashes and line dash offsets perhaps and see where that gets you.  Does that make sense, at least sort of?  😸

**Comment by notflip** [comment]
Thanks for the information! I'm going to take a look very soon!
