### ISSUE TITLE
geodesic lines

### ISSUE THREAD

**Issue by rutgerhofste** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#12]
Cool project but is there a way to swap Bezier lines for geodesic lines that are an accurate approximation for this projection?

**Comment by jwasilgeo** [comment]
Thanks.  Geodesic lines are inherently a different paradigm/concept that isn't the purpose or within the scope of this project.  You can use something else for Leaflet, such as:

- https://github.com/henrythasler/Leaflet.Geodesic
- https://github.com/springmeyer/arc.js
- https://github.com/MAD-GooZe/Leaflet.Arc
