### ISSUE TITLE
Any tips on how to add the cdn to an angular 6 app which has leaflet and esri-leaflet installed and working via npm ?

### ISSUE THREAD

**Issue by vishalseshagiri** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#16]
- I know that I have to somehow block the execution of the cdn till leaflet gets loaded but I am not able to figure out how to do that. Help would be really appreciated, btw this is a really awesome viz big fan !
Error trace.
> core.js:12584 ERROR TypeError: leaflet__WEBPACK_IMPORTED_MODULE_1__.canvasFlowmapLayer is not a function
>     at Object.complete (location-maps.component.ts:193)
>     at d.parseChunk (papaparse.min.js:7)
>     at d._chunkLoaded (papaparse.min.js:7)
>     at XMLHttpRequest.__zone_symbol__ON_PROPERTYload (papaparse.min.js:7)
>     at XMLHttpRequest.wrapFn (zone.js:1188)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
>     at Object.onInvokeTask (core.js:14134)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
>     at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:496)

**Comment by vishalseshagiri** [comment]
I figured it out, here's what I am doing, just in case someone stumbles on this in the future:

Install leaflet and esri-leaflet via npm.

```
npm i leaflet
npm i esri-leaflet

```
Add Tween.min.js to index.html
`<script src="https://cdnjs.cloudflare.com/ajax/libs/tween.js/17.2.0/Tween.min.js"></script>
`

Import Leaflet and Esri-leaflet to your component as such : 
```
import * as L from 'leaflet';
import * as esri from 'esri-leaflet';
import { } from 'leaflet-routing-machine';
```

Import CanvasFlowmapLayer.js using cdn as such : 

```
ngOnInit() {
   get('https://jwasilgeo.github.io/Leaflet.Canvas-Flowmap-Layer/src/CanvasFlowmapLayer.js', () => {
       // All your logic goes here
   }
}
```
This way the CanvasFlowmapLayer loads after window.L has been initialized.

Also you should get a types error in angular 6, you can fix it by adding the following types declaration to the @types/leaflet/index.d.ts file : 
`export function canvasFlowmapLayer(originAndDestinationGeoJsonPoints: any, opts?: any): any;`

**Comment by vishalseshagiri** [comment]
![posse](https://user-images.githubusercontent.com/12839518/48661497-8b825a00-ea27-11e8-8a01-cde753b0c582.gif)

**Comment by vishalseshagiri** [comment]
please find types fix here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30614

**Comment by alejo90** [comment]
I do not believe that github.io site's script is meant to be used the way you are intending to. Since this library doesn't seem to be hosted as an npm package, the preferred approach would be to download the javascript file and include it into your project. You can then import it normally and angular will include it in the resulting bundle.

**Comment by jwasilgeo** [comment]
@vishalseshagiri thanks so much for the kind words and I'm glad you want to use this plugin!

@alejo90, thanks also for joining the discussion and providing some more advice and input.  I agree that the github.io approach isn't necessarily intended to be used as a CDN for long-term and production situations.

One day I would definitely like to publish this as an npm package to make it easier for everyone to access and consume.  I welcome contributions for that if anyone wants to beat me to it and do it first!  😄
