### ISSUE TITLE
How to set different color for each animatedCanvasBezierStyle points ?

### ISSUE THREAD

**Issue by oijkn** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#18]
Hello, 

First of all I want to thank you for this wonderful lib :)

I'm trying to set a different color for each point of `animatedCanvasBezierStyle ` as like `canvasBezierStyle` with the option _classBreakInfos_ but it doesn't work. I also tried to modify the  function of `_animateCanvasLineSymbol` for _symbolObject.strokeStyle_ but it's not better...

Like bellow, I would like to set color of animated point with the same color of lines.

![image](https://user-images.githubusercontent.com/18188407/56863021-65d38680-69b1-11e9-924f-8bd50daffff5.png)

Could someone help me please ?

Best regards.

**Comment by oijkn** [comment]
Hi,

Any news please ? Thx

BR.

**Comment by jwasilgeo** [comment]
Hi @oijkn thanks for the kind words and also thanks for your patience.  Can you please create some kind of live code example that I could look at and try to modify to help answer your question?  JSBin, Codepen, etc.

**Comment by oijkn** [comment]
Hi @jwasilgeo ,

Thank you for helping to find a solution to my problem.

Here is a live example that you could look at and try to modify : [codepen demo](https://codepen.io/anon/pen/qGvOPL?editors=0010)

To display the animated lines you have to click on the area ;)

Thank you for your support and help.

BR.

**Comment by jwasilgeo** [comment]
I think I might have a solution in an upcoming code change.  Here is a screenshot:

![image](https://user-images.githubusercontent.com/4933392/58890449-3d296580-86b0-11e9-9c5e-927968c92ac9.png)

I do not know how this will impact animation performance when there are many features to draw and animate on the map.  But, at the moment, to at least be able to support unique animation styles beyond just the "simple" style, I will push a change soon.
