### ISSUE TITLE
no need to maintain a gh-pages branch anymore

### ISSUE THREAD

**Issue by jgravois** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#2]
you can host pages directly from `master` now.

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by jwasilgeo** [comment]
@jgravois that's really good to know, thanks! I have tried hosting from `master` with mixed results. Perhaps the github universe is still churning on some of the files required for the "main" demo in this repo?  It won't (yet) load the src js file for the custom layer nor the data demo csv file.

**Comment by jwasilgeo** [comment]
Update: so for now, I've set it back to work with `gh-pages` branch.  Feel free to experiment with it if you feel so inclined.

**Comment by jgravois** [comment]
> Feel free to experiment with it if you feel so inclined.

i don't have sufficient privileges to change those settings (unless an organization is used, only one [owner/admin](https://help.github.com/articles/permission-levels-for-a-user-account-repository/) can be designated).

this isn't crucial.

**Comment by jwasilgeo** [comment]
✋- 5

**Comment by jwasilgeo** [comment]
Follow up: serving from `master` now seemingly without any problems.
