### ISSUE TITLE
Add function to reset the canvas and show all flows - new feature

### ISSUE THREAD

**Issue by diggydiggyhole** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#21]
Hello !
First I would like to thank you for the amazing work you have done on this project.

While using it I discovered that there was no possibility to show all flows from origin to destination so I ended created one and adding it to the source code.

It is directly inspired from clearAllPathSelections but instead of taking everything away it will show everything.
Here is the code put just below clearAllPathSelections :
```js
resetAllPathSelections: function() {
        this.originAndDestinationGeoJsonPoints.features.forEach(function(feature) {
          if (feature.properties.isOrigin === true) {
            feature.properties._isSelectedForPathDisplay = true;
          } else {
            feature.properties._isSelectedForPathDisplay = false;
          }
        });
  
        this._resetCanvas();
      },
```
It can be used on a reset button on leaflet.

Thanky you again.

**Comment by jwasilgeo** [comment]
Thank you for the nice feedback and for the good idea, @diggydiggyhole! I'll try to find some time soon to bring this in to the layer's code.
