### ISSUE TITLE
Vue js + Leaflet.Canvas-Flowmap-Layer

### ISSUE THREAD

**Issue by bonya0329** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#26]
Hello
Can I find out how to connect this library in a Vue js project?
Please help me urgently to find a way out of the situation. I really want to use your library.

**Comment by jwasilgeo** [comment]
Hi @bonya0329, for this repository I haven't yet done any formal package management and publishing to npm. For now, you could download the entire repository and bring in the [main source code JS file](https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/blob/master/src/CanvasFlowmapLayer.js) into your own Vue project setup.

I'm not sure about Vue specifically, but here is a plain HTML/JS line of code for importing it globally and it would be added to the `L` LeafletJS global namespace: https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/blob/master/docs/main/index.html#L45

Which could be used like this: https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/blob/master/docs/main/index.html#L81

**Comment by bonya0329** [comment]
Thank you for your answer, Hallelujah, I was able to do it. :)
![image](https://user-images.githubusercontent.com/60532283/130896510-2f9d22b9-3950-4ee8-a80b-479fdbf9a8b4.png)
