### ISSUE TITLE
move to Esri org?

### ISSUE THREAD

**Issue by jgravois** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#3]
is this something you want to do?  (i hope so)

**Comment by jgravois** [comment]
obviously its not _technically_ an Esri Leaflet plugin, but i'd love to show it off there wherever it ultimately ends up being hosted.

https://esri.github.io/esri-leaflet/plugins/

**Comment by jwasilgeo** [comment]
@sarahbellum and I are hyped about your idea to show it off and help us spread the word!  Thanks!

We were thinking to maintain them (the CFL repos for LeafletJS and JSAPI) under our respective user accounts for now, but fork them to the Esri org if desired by others.  And we're fine with taking on the onus of keeping any Esri forks up to date.

Additional thoughts @sarahbellum @jgravois?

**Comment by jgravois** [comment]
i don't see the point of forking if the codebase doesn't need to diverge. no worries if you'd like to keep them where they are.

**Comment by jwasilgeo** [comment]
Cool, sounds good @jgravois. Let's :shipit: from here then. Thanks for the ideas and thoughts.
