### ISSUE TITLE
Adding and removing layers from a map causes slowdown

### ISSUE THREAD

**Issue by shivishivi1997** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#5]
If a layer is removed from a map, and then added, repeatedly, it causes the animations and website to slowdown substantially.

Possible issue with something not being removed each time?

**Comment by jwasilgeo** [comment]
Thanks for bringing this to my attention.  Could certainly be something I missed.  I don't know how soon I can investigate this myself, but the first place I would look is at the `onRemove` method and compare it to the `onAdd` method to see if something isn't being removed, as you suggest.

https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/blob/master/src/CanvasFlowmapLayer.js#L214-L261

If you have a public sample that reproduces this problem (like on jsfiddle, jsbin, etc.) that you can share, that would be a huge step forward in researching this.

Thanks!

**Comment by shivishivi1997** [comment]
Had a quick look through them, and all looks good to me! Very odd.

Will put up a jsfiddle in a bit. Thanks

**Comment by shivishivi1997** [comment]
Looks like something to do with Composite Layers according to Chrome

**Comment by wonyun** [comment]
I have the same problem~

**Comment by HxqEmma** [comment]
I have the same problem~

**Comment by jwasilgeo** [comment]
Can you all tell me more about what is in your DOM?  Specifically, what are the DOM elements in your `<div class="leaflet-pane leaflet-overlay-pane">` when you first add this layer to the map, what does it look like when you remove it, and then what does it look like when you add it back in again?

Can someone please provide a public sample that reproduces the issue?

**Comment by wonyun** [comment]
@jwasilgeo https://codepen.io/fetest/pen/yzOGpj?editors=0010

click the polygon area more than 4 times, you can find the canvas animation slowdown, meanwhile the start position of canvas animation has changed. 

Looking forward to your reply, thank you very much！

**Comment by jwasilgeo** [comment]
@wonyun thank you for creating the sample reproducing this.  Actually, I am beginning to wonder if this and #10 are related to each other.  I'll try to find time over the next week or so to figure this out.  Thanks everyone.  My first thought is that I'll make sure the code resets some internal tracking property values during `onAdd` to the map.

**Comment by wonyun** [comment]
@jwasilgeo 
Looking forward to solving this problem ASAP, thanks!

**Comment by jwasilgeo** [comment]
I *think* this has been fixed in the recent commit to master f89fc9395c0d85e20f50a7a0c346e15641b3874a.  Can you please verify?  Perhaps soon I'll release a "v1" of this project.

**Comment by jwasilgeo** [comment]
Ok, closing for now.
