### ISSUE TITLE
Path weight snippet?

### ISSUE THREAD

**Issue by mfortini** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#7]
I'm not a JS expert, but I could create a really nice quick flow map, thank you.
I wanted to vary the lines' widths according to a weight, but I couldn't find any example.
Could you add such a feature? Thank you.

**Comment by jwasilgeo** [comment]
I'm glad you are trying out this library!  What you're asking for is indeed supported and possible, but I agree that without an example it isn't very clear what to do.  We'll create a new sample page sometime soon to share with the :world_map:.

cc @sarahbellum

**Comment by jwasilgeo** [comment]
@mfortini there's a new demo that does class breaks of the canvas lines:
- https://jwasilgeo.github.io/Leaflet.Canvas-Flowmap-Layer/docs/class-breaks-symbology
- source code is here and please focus on these lines: https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/blob/master/docs/class-breaks-symbology/index.html#L94-L137

The object specification is actually modeled after Esri's [ArcGIS REST API renderer json specification](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Renderer_objects/02r30000019t000000/). 
 Simple, unique value, and class breaks are all supported but instead use canvas stroke and line style property names.

**Comment by Zahma** [comment]
@mfortini I suggest you to extend the Library by modifying the the following function, you can calculate the strokewidth (which is in your case I presume weight) and maybe multiply it by a factor (either linear or not):

```
applyAnimatedCanvasLineSymbol: function(ctx, symbolObject, screenOriginPoint, screenDestinationPoint, strokewidth) {
                     ctx.lineCap = symbolObject.lineCap;
                     ctx.strokeStyle = symbolObject.strokeStyle;
                     ctx.lineWidth = strokewidth * 4;   // HERE
                     ctx.shadowBlur = symbolObject.shadowBlur;
                     ctx.shadowColor = symbolObject.shadowColor;
                     ctx.moveTo(screenOriginPoint.x, screenOriginPoint.y);
                     ctx.bezierCurveTo(screenOriginPoint.x, screenDestinationPoint.y, screenDestinationPoint.x, screenDestinationPoint.y, screenDestinationPoint.x, screenDestinationPoint.y);
                 }
```
I don't know what @jwasilgeo thinks of this.

**Comment by jwasilgeo** [comment]
@Zahma the source code you point out is indeed where the canvas symbol properties are being set just before an updated drawing of a flowline on the canvas.

But @mfortini, if you can follow the new example I created of how to set these kinds of properties when creating and adding the layer to the map without having to alter this layer's source code, I think that will serve you well.

The catch here is that this Leaflet version of the Canvas-Flowmap-Layer **and** the [Esri-compatible Canvas-Flowmap-Layer](https://github.com/sarahbellum/Canvas-Flowmap-Layer) both apply **flowline symbols** based on this info (from the other repo):

> Symbol configurations are defined using property objects inspired by the ArcGIS REST API renderer objects specification. Simple, unique value, and class breaks are all supported but instead use canvas stroke and line style property names.

http://resources.arcgis.com/en/help/arcgis-rest-api/#/Renderer_objects/02r30000019t000000/


  Let me know if you have any additional questions.  Thanks all.
